name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings -D rustdoc -D missing_docs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run rustfmt with check mode
      run: |
        cargo fmt -- --check

    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D clippy::pedantic -D clippy::all

    - name: Build
      run: cargo build
